version: '3.8'

services:
  mongo:
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: prisma